name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.8.0

      - name: Test
        run: |
          npm install
          npm test

      - name: Build
        run: |
          npm run build
