name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: volta-cli/action@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Tests
        run: |
          npm test

      - name: Build
        run: |
          npm run build

      - name: Type Documentation
        run: |
          npm run doc

      - name: Deploy documentation 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation
