name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.8.0

      - name: Install dependencies
        run: |
          npm install

      - name: Tests
        run: |
          npm test

      - name: Build
        run: |
          npm run build

      - name: Type Documentation
        run: |
          npm run doc

      - name: Deploy documentation 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation
