name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: volta-cli/action@v3

      - name: Install dependencies
        run: |
          node --version
          npm --version
          npm ci

      - name: Tests
        run: |
          npm test

      - name: Build
        run: |
          npm run build
